### ISSUE TITLE
Crash: ActivityNotFoundException  act=android.intent.action.VIEW dat=https://github.com/

### ISSUE THREAD

**Issue by Nodrex** [Nodrex/Testomania#190]
Firs crash reported from crashalitycs:

`Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://github.com/... }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2087)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
       at android.app.Activity.startActivityForResult(Activity.java:5404)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java)
       at android.app.Activity.startActivityForResult(Activity.java:5362)
       at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java)
       at android.app.Activity.startActivity(Activity.java:5748)
       at androidx.core.content.ContextCompat$Api16Impl.startActivity(ContextCompat.java)
       at androidx.core.content.ContextCompat.startActivity(ContextCompat.java:2)
       at com.earth.testomania.presentation.AboutBottomSheetKt$AboutBottomSheet$1.invoke(AboutBottomSheetKt.java:2)
       at com.earth.testomania.presentation.AboutBottomSheetKt$AboutBottomSheet$1.invoke(AboutBottomSheetKt.java:2)
       at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(ClickableKt.java:2)
       at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetectorKt.java:7)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:8)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTaskKt.java:75)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTaskKt.java:7)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.java:7)
       at kotlinx.coroutines.CancellableContinuationImpl.C(CancellableContinuationImpl.java:41)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.java:3)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.java:11)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.java:5)
       at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.i(SuspendingPointerInputFilter.java:8)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Node.java:9)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Node.java:7)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Node.java:7)
       at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(Node.java:7)
       at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(NodeParent.java:3)
       at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.java:4)
       at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.java:16)
       at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.java:10)
       at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.java:6)
       at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.java:68)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
       at android.app.Activity.dispatchTouchEvent(Activity.java:4196)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
       at android.view.View.dispatchPointerEvent(View.java:14799)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6347)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6148)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5626)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5814)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5871)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5683)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5649)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5657)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5630)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8562)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8513)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8482)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8685)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:161)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7839)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

https://console.firebase.google.com/u/0/project/testomania-e42a4/crashlytics/app/android:com.earth.testomania/issues/50b7d2dedd98268ab0ff54db5d9e61fa?time=last-seven-days&sessionEventKey=63052630022D0001204036127AC2EFF6_1713596900422683825

**Comment by Nodrex** [comment]
https://stackoverflow.com/questions/5882656/no-activity-found-to-handle-intent-android-intent-action-view#:~:text=For%20me%20when%20trying%20to%20open%20a%20link%20%3A

**Comment by shalva97** [comment]
I think it happened on Emulator. sdk_goog3_x86_64 is the device. Anyways we could add a check for this so at least app does not crash

**Comment by Nodrex** [comment]
> I think it happened on Emulator. sdk_goog3_x86_64 is the device. Anyways we could add a check for this so at least app does not crash

Yes totally agree we need to add a crash handler and show an appropriate snackBar or Toast
